DROP TABLE IF EXISTS "Detailed-Data-Scheme";

CREATE TABLE "Detailed-Data-Scheme" (
       Sector	 VARCHAR(50),
       Sub-sector	VARCHAR(50),
       Emissions source definition	VARCHAR(50),
       Data available through:	VARCHAR(50),
       source_id	VARCHAR(255),
       source_name	VARCHAR(255),
       source_type	VARCHAR(255),
       iso3_country	VARCHAR(255),
       original_inventory_sector	VARCHAR(255),
       start_time	VARCHAR(255),
       end_time	VARCHAR(255),
       lat	VARCHAR(50),
       lon	VARCHAR(50),
       geometry_ref	VARCHAR(50),
       gas	VARCHAR(255),
       emissions_quantity	VARCHAR(255),
       temporal_granularity	VARCHAR(255),
       activity	VARCHAR(255),
       activity_units	VARCHAR(255),
       emissions_factor	VARCHAR(255),
       emissions_factor_units	VARCHAR(255),
       capacity	VARCHAR(255),
       capacity_units	VARCHAR(255),
       capacity_factor	VARCHAR(255),
       capacity_factor_units	VARCHAR(255),
       other1	VARCHAR(255),
       other1_def	VARCHAR(255),
       other2	VARCHAR(255),
       other2_def	VARCHAR(255),
       other3	VARCHAR(255),
       other3_def	VARCHAR(255),
       other4	VARCHAR(255),
       other4_def	VARCHAR(255),
       other5	VARCHAR(255),
       other5_def	VARCHAR(255),
       other6	VARCHAR(255),
       other6_def	VARCHAR(255),
       other7	VARCHAR(255),
       other7_def	VARCHAR(255),
       other8	VARCHAR(255)
       other8_def	VARCHAR(255),
       other9	VARCHAR(255),
       other9_def	VARCHAR(255),
       other10	VARCHAR(255),
       other10_defVARCHAR(255),
       created_date	VARCHAR(255),
      modified_date VARCHAR(255)
);